modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "command_waypoints"
version = "${version}"
displayName = "Command Waypoints"
authors = "Jakob (Minenash)"
description = '''
Allows you to create waypoints using a command without any entities
'''
#logoFile = ""

[[dependencies.command_waypoints]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.command_waypoints]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "command_waypoints.mixins.json"
